### ISSUE TITLE
Object Mapper 

### ISSUE THREAD

**Issue by vel1024** [temp-portfolio-team/backend#2]
Object Mapper 라이브러리로 Mapstruct 를 쓰려고 하는데 어떠신가요?
선정한 이유는 아래 링크 참조해주시면 좋을 것 같습니다.
[https://meetup.toast.com/posts/213](https://meetup.toast.com/posts/213)

그리고 앞으로 어떤 프로젝트 관련 질문이나 
개발 관련 이슈는 모두 issues 에 올려주시면 좋을 것 같습니다.

**Comment by ehgns852** [comment]
네 확인 했습니다.
